### ISSUE TITLE
Support for PAM Yubico

### ISSUE THREAD

**Issue by kees-closed** [SUSE/pam-config#27]
It looks like there is no support yet for PAM Yubico (pam_yubico.so).
More info: https://developers.yubico.com/yubico-pam/

An example from my `sshd` service in `/etc/pam.d`:

`auth       required     pam_yubico.so id=16 authfile=/etc/security/otp_maps`

Where the `otp_maps` could look like:
`user:cccccctwhsbc`

**Comment by thkukuk** [comment]
pam_yubico.so is per service, you don't want that for all services (else you would need to authenticate every cron job with your key).
pam-config does not really support single services, the minimal existing support is deprecated and unmaintained. And 
pam-config does not create additional configuration files.
So as long as nobody steps up and implements full support for "single services" in pam-config and not only common-* files, there is no way to add this module.

**Comment by thkukuk** [comment]
pam-config is for configuring the common PAM config, not for special services and never was designed as this, even if there was the try to enhance it this way.

Else I don't understand your comments. Since the single service files (so not starting with common-*)are  not under control of pam-config, you can edit them in the same way as with every other distribution.
And since PAM is quite complex, you should understand what you are doing and not just copy&paste something in the hope it will work and not make your system insecure.
